[program:hwoj-backend]
command=<path to backend virtualenv>/bin/fastapi run
directory=<path to backend>
stopsignal=QUIT
stdout_logfile=/tmp/hwoj-backend.stdout.log
stderr_logfile=/tmp/hwoj-backend.stderr.log