[program:hwoj-discordbot]
command=<path to discordbot>/.venv/bin/python app.py
directory=<path to discordbot>
stopsignal=QUIT
stdout_logfile=/tmp/hwoj-discordbot.stdout.log
stderr_logfile=/tmp/hwoj-discordbot.stderr.log