[program:hwoj-judge]
command=<path to judge>/.venv/bin/python main.py --name=box%(process_num)02d --box_id=%(process_num)02d --work_dir=/tmp/hwoj-judge/box%(process_num)02d
directory=<path to judge>
stopsignal=QUIT
stdout_logfile=/tmp/hwoj-judge-%(process_num)02d.stdout.log
stderr_logfile=/tmp/hwoj-judge-%(process_num)02d.stderr.log
user=oj
numprocs=4
process_name=box_%(process_num)02d
