[program:hwoj-backend]
command=<path to backend>/.venv/bin/uvicorn main:app
directory=<path to backend>
stopsignal=QUIT
stdout_logfile=/tmp/hwoj-backend.stdout.log
stderr_logfile=/tmp/hwoj-backend.stderr.log