[program:hwoj-judge]
command=<path to judge>/.venv/bin/fastapi run
directory=<path to judge>
stopsignal=QUIT
stdout_logfile=/tmp/hwoj-judge.stdout.log
stderr_logfile=/tmp/hwoj-judge.stderr.log
user=oj
numprocs=4
process_name=%(program_name)s_%(process_num)02d