server {
    listen 80;
    listen [::]:80;
    
    server_name <yourdomain.com>;

    # Frontend - react files
    location / {
        root <dist_folder>; // Permisson error: chmod or copy dist to /var/www/my-app
        index index.html index.htm;
        try_files $uri $uri/ /index.html; 
    }
    

    # Backend
    location /api/ {
        proxy_pass http://localhost:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
