server {
    listen 80;
    listen [::]:80;
    
    server_name test.hw.io.vn;

    # Frontend - react files
    # Note: Ensure /var/www/my-app has correct read permissions for www-data
    location / {
        root /var/www/my-app; 
        index index.html;
        try_files $uri $uri/ /index.html; 
    }

    # Backend
    location /api/ {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://localhost:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}