[program:hwoj-judge]
command=/home/oj/HWOJ/judge/.venv/bin/python main.py
directory=/home/oj/HWOJ/judge
stopsignal=QUIT
stdout_logfile=/home/oj/HWOJ/tmp/hwoj-judge.stdout.log
stderr_logfile=/home/oj/HWOJ/tmp/hwoj-judge.stderr.log
user=oj
numprocs=3
process_name=box_%(process_num)02d