[program:hwoj-backend]
command=/home/oj/HWOJ/backend/.venv/bin/uvicon main:app
directory=/home/oj/HWOJ/backend
stopsignal=QUIT
stdout_logfile=/home/oj/HWOJ/tmp/hwoj-backend.stdout.log
stderr_logfile=/home/oj/HWOJ/tmp/hwoj-backend.stderr.log